openapi: 3.0.3
info:
  title: Local Discovery Assistant API
  version: 0.1.0
servers:
  - url: http://localhost:7003
paths:
  /suggest:
    post:
      summary: Stream grounded suggestions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transcript:
                  type: string
                limit:
                  type: integer
                  default: 3
              required:
                - transcript
      responses:
        '200':
          description: Server-sent events stream
          content:
            text/event-stream:
              schema:
                type: string
  /ingest:
    post:
      summary: Ingest documents into retrieval store
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                directory:
                  type: string
      responses:
        '200':
          description: Ingestion result
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  result:
                    type: object
                    properties:
                      processed:
                        type: integer
                      sources:
                        type: array
                        items:
                          type: string
  /telemetry:
    post:
      summary: Record overlay telemetry events
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accepted:
                  type: boolean
                latency:
                  type: number
                  description: Milliseconds between transcript and suggestion delivery
              required:
                - accepted
                - latency
      responses:
        '200':
          description: Telemetry recorded
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
components:
  schemas:
    Evidence:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        source:
          type: string
        span:
          type: array
          items:
            type: integer
          minItems: 2
          maxItems: 2
        rerankScore:
          type: number
    SuggestionStreamChunk:
      type: object
      properties:
        token:
          type: string
        done:
          type: boolean
        intent:
          type: string
          enum: [requirements, architecture, integration, risk, generic]
        evidence:
          type: array
          items:
            $ref: '#/components/schemas/Evidence'
        latency:
          type: number
    SuggestionPayload:
      type: object
      properties:
        suggestions:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              text:
                type: string
              confidence:
                type: number
              evidence:
                type: array
                items:
                  type: string
