name: CI (nox)

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'project_generator/**'
      - '.github/workflows/ci-nox.yml'
  push:
    branches: [ main ]
    paths:
      - 'project_generator/**'
      - '.github/workflows/ci-nox.yml'
  workflow_dispatch:
    inputs:
      run_fastapi:
        description: "Run FastAPI template tests"
        required: false
        default: 'false'
      run_django:
        description: "Run Django template tests"
        required: false
        default: 'false'
      run_next:
        description: "Run Next.js template tests"
        required: false
        default: 'false'
      run_angular:
        description: "Run Angular template tests"
        required: false
        default: 'false'

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install nox
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Run generator session (default)
        run: nox -s generator
      - name: Upload artifacts (optional)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./.nox/**/log*
      - name: Run FastAPI template tests
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_fastapi == 'true' }}
        run: nox -s fastapi
      - name: Run Django template tests
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_django == 'true' }}
        run: nox -s django
      - name: Run Next.js template tests
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_next == 'true' }}
        run: nox -s next
      - name: Install Chromium (for Angular)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_angular == 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium
          echo "CHROME_BIN=$(command -v chromium-browser || command -v chromium)" >> $GITHUB_ENV
      - name: Run Angular template tests
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_angular == 'true' }}
        env:
          CHROME_BIN: ${{ env.CHROME_BIN }}
        run: nox -s angular

