name: Secrets Preflight

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  secrets-preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Verify required secrets and variables
        shell: bash
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ECS_EXECUTION_ROLE_ARN: ${{ secrets.AWS_ECS_EXECUTION_ROLE_ARN }}
          AWS_ECS_TASK_ROLE_ARN: ${{ secrets.AWS_ECS_TASK_ROLE_ARN }}
          APP_NAME: ${{ vars.APP_NAME }}
          ECS_CLUSTER_NAME: ${{ vars.ECS_CLUSTER_NAME }}
          ECS_SERVICE_NAME: ${{ vars.ECS_SERVICE_NAME }}
          FRONTEND_URL_STAGING: ${{ vars.FRONTEND_URL_STAGING }}
          API_URL_STAGING: ${{ vars.API_URL_STAGING }}
          DB_URL_STAGING: ${{ vars.DB_URL_STAGING }}
          FRONTEND_URL_PRODUCTION: ${{ vars.FRONTEND_URL_PRODUCTION }}
          API_URL_PRODUCTION: ${{ vars.API_URL_PRODUCTION }}
          DB_URL_PRODUCTION: ${{ vars.DB_URL_PRODUCTION }}
        run: |
          set -euo pipefail
          missing=0
          require() {
            local var_name="$1"
            if [[ -z "${!var_name:-}" ]]; then
              echo "Missing ${var_name}" >&2
              missing=1
            fi
          }

          require VERCEL_TOKEN
          require VERCEL_ORG_ID
          require VERCEL_PROJECT_ID
          require AWS_REGION
          require AWS_ECS_EXECUTION_ROLE_ARN
          require AWS_ECS_TASK_ROLE_ARN
          require APP_NAME
          require ECS_CLUSTER_NAME
          require ECS_SERVICE_NAME
          require FRONTEND_URL_STAGING
          require API_URL_STAGING
          require DB_URL_STAGING
          require FRONTEND_URL_PRODUCTION
          require API_URL_PRODUCTION
          require DB_URL_PRODUCTION

          if [[ $missing -ne 0 ]]; then
            echo "Secrets/vars preflight failed" >&2
            exit 1
          fi

          echo "All required secrets and variables are present"
