name: Test

on:
  workflow_call: {}

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run full stack tests with coverage
        env:
          CI: true
        run: make test

      - name: Upload aggregated coverage summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-summary
          path: coverage/coverage-summary.json
          if-no-files-found: warn

      - name: Upload backend coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: coverage/backend-coverage.xml
          if-no-files-found: warn
